dist: bionic
language: java
jdk: openjdk11

addons:
   sonarcloud:
      organization: "predictabowl"
      token: $SONAR_TOKEN

#skip installation step
install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache 
      
      
script:
   - mvn clean verify sonar:sonar -Dsonar.projectKey=Predictabowl_travis-sonarcloud.test